[package]
name = "rs"
version = "0.1.0"
authors = ["fuziki <fzk@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.3.0"